### ISSUE TITLE
No longer working after Big Sur update.

### ISSUE THREAD

**Issue by pkdesign** [Goldfish64/SystemProfilerMemoryFixup#6] opened 2021-04-07 18:18 UTC
After updating to Big Sur, kext does not seems to work any longer. I don not see Memory tab on System Info.

**Comment by Goldfish64** [comment] 2021-04-07 21:24
Duplicate of https://github.com/Goldfish64/SystemProfilerMemoryFixup/issues/5. Lilu currently does not support userspace patching under Big Sur.

**Closed as completed by Goldfish64** 2021-04-07 21:24 UTC
